apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ehd58d8pl-python
  janus-idp.io/tekton: ehd58d8pl-python
  backstage.io/kubernetes-id: ehd58d8pl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehd58d8pl-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
