apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ehd58d8pl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ehd58d8pl-python 
  name: ehd58d8pl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ehd58d8pl-python 
